export const SEARCH_MOVIES_START = 'SEARCH_MOVIES_START'
export const SEARCH_MOVIES_FAILED = 'SEARCH_MOVIES_FAILED'
export const SEARCH_MOVIES_SUCESS = 'SEARCH_MOVIES_SUCESS'

export const SEARCH_MORE_MOVIES_START = 'SEARCH_MORE_MOVIES_START'
export const SEARCH_MORE_MOVIES_FAILED = 'SEARCH_MORE_MOVIES_FAILED'
export const SEARCH_MORE_MOVIES_SUCESS = 'SEARCH_MORE_MOVIES_SUCESS'

export const GET_MOVIES_Genres_START = 'GET_MOVIES_Genres_START'
export const GET_MOVIES_Genres_FAILE = 'GET_MOVIES_Genres_FAILED'
export const GET_MOVIES_Genres_SUCESS = 'GET_MOVIES_Genres_SUCESS'